/** @type {import('tailwindcss').Config} */
module.exports = {
  darkMode: "class",
  content: [
    "./pages/**/*.{js,ts,jsx,tsx}",
    "./components/**/*.{js,ts,jsx,tsx}",
  ],
  theme: {
    colors: {
      transparent: 'transparent',
      current: 'currentColor',
      'white': '#ffffff',
      'purple': '#3f3cbb',
      'midnight': '#121063',
      'metal': '#565584',
      'tahiti': '#3ab7bf',
      'silver': '#ecebff',
      'bubble-gum': '#ff77e9',
      'bermuda': '#78dcca',
      'eggshell': '#F4F1DE',
      'deepchampagne': '#F2CC8F',
      'terracotta': '#E07A5F',
      'greensheen': '#81B29A',
      'independencepetrol': '#3D405B',
      'cornflowerblue': '#89A1EF',
      'carolinablue': '#00A5E0',
      'vividskyblue': '#32CBFF',
      'yelloworange': '#FFA630',
      'tyrianpurple': '#611C35',
      'brightred': '#DB3A34',
      'jet': '#323031',
      'beige': '#DCE2C8',
      'brightblazeorange': '#F96900',
      'princetonorange': '#F17F29',
      'congomattepink': '#FE938C',
      'tumbleweed': '#EDAF97',
      'graylilac': '#AD91A3',
      'pistachio': '#90BE6D',
      'teagreen': '#C9E3AC',
      'bloodred': '#69140E',
      'rust': '#A44200',
      'bronze': '#D58936',
      'lemonyellow': '#FFF94F',
      'darkpurple': '#27213C',
      'rosewood': '#570000',
      'buffyellow': '#EFD28D',
      'bananamania': '#F7E3AF',
      'pucepink': '#C08497',
      'slategray': '#748386',
      'greypurple': '#BDB4BF',
    },
    extend: {
      fontFamily: {
         burtons: "burtons",
         butler: "Butler",
         indie: "indie",
         chriselda: "chriselda",
         cartograph: "cartograph",
         blackbird: "blackbird",
         sacramento: "sacramento",
         consolas: "Consolas",
         reddrains: "redrains",
      },
    },
  },
  plugins: [],
};
