import Head from 'next/head';
import {BsFillMoonStarsFill} from 'react-icons/bs';
import {AiFillTwitterCircle, AiFillLinkedin, AiFillYoutube} from "react-icons/ai";
import Image from 'next/image';
import logo from '../public/logo.svg';
import ThreeD from '../public/dude.png';
import coffeedesign from '../public/logo1.svg';
import designer from '../public/logo2.svg';
import salon from '../public/logo3.svg';
import day1 from '../public/1.png';
import day2 from '../public/2.png';
import day3 from '../public/3.png';
import day4 from '../public/4.png';
import day5 from '../public/5.png';
import day6 from '../public/6.png';
import day7 from "../public/7.png";
import day8 from "../public/8.png";
import day9 from "../public/9.png";
import day10 from "../public/10.png";
import day11 from "../public/11.png";
import day12 from "../public/12.png";
import { useState } from 'react';
import motion from 'framer-motion';



export default function Home() {
  const [darkMode, setDarkMode]=useState(false);
  return (
    <div className={darkMode? 'dark' : ""}>
      <Head>
        <title>Anurag Das</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className='bg-eggshell px-10 md:px-20 lg:px-40 dark:bg-gray-90'>
        <section className= "min-h-screen">
          <nav className="py-5 px-1 mb-12 flex justify-between">
            <div className='flex left-5'>
            <Image src={logo} alt="" width={75} height={75} />
            </div>
            <ul className='flex items-center'>
              <li>
                <BsFillMoonStarsFill onclick={() =>setDarkMode(!darkMode)}className='cursor-pointer text-2xl'/>
              </li>
              <li><a className='bg-gradient-to-r from-deepchampagne to-terracotta text-eggshell px-4 py-2 rounded-lg ml-8' href="#">Resume</a></li>
            </ul>
          </nav>
          <div className='text-center p-10'>
            <h2 className='text-9xl font-sacramento py-4 text-brightred md:text-6xl'>Anurag Das</h2>
            <h3 className='text-3xl text-greensheen font-chriselda py-10 md:text-3xl'>Designer and Developer.</h3>
            <p className='text-md font-reddrains font-medium py-4 leading-10 text-jet md:text-xl max-w-screen-lg mx-auto'>A Man Without Purpose, Distracts Himself With Cheap Pleasure.</p>
          </div>
          <div className='text-5xl flex justify-center gap-16 py-3 text-gray-400'>
            <AiFillTwitterCircle />
            <AiFillLinkedin />
            <AiFillYoutube />
          </div>
          <div className='mx-auto bg-gradient-to-b from-yellow-500 to-yellow-200 rounded-full w-80 h-80 relative overflow-hidden mt-20 md:h-96 md:w-96'>
            <Image src={ThreeD} alt="" fill cover/>
          </div>
        </section>

        <section>
          <div>
            <h3 className='text-4xl font-blackbird text-tyrianpurple py-2 px-2 mt-10'>ArtWorks</h3>
            <p className='text-xl font-medium py-2 px-2 leading-8 text-jet font-reddrains mt-3 mb-9'>
              If <span className='text-terracotta'>Picasso</span> was a digital artist, do you think he would come up with something like this?
              <span className=''> Anyway, check out the designs xD.</span>
            </p>
          </div>
          <div className='lg: flex gap-x-17 mb-9'>
            <div className='text-center justify-center shadow-lg px-10 rounded-xl my-1 mx-3 bg-gradient-to-r from-buffyellow to-bananamania'>
              <div className='flex justify-center'>
              <Image src={coffeedesign} alt="" width={150} height={150}/>
              </div>
               <h3 className='text-lg font-butler text-rosewood pb-2'>Creative Designs</h3>
               <p className='py-2 font-consolas text-jet text-opacity-85'>
                {" "}
                Creating elegant designs suited for your needs following core design theory.
               </p>
            </div>
            <div className='text-center justify-center shadow-lg px-10 rounded-xl my-1 mx-3 bg-gradient-to-r from-buffyellow to-bananamania'>
              <div className='flex justify-center'>
              <Image src={designer} alt="" width={150} height={150}  />
              </div>

               <h3 className='text-lg font-butler text-rosewood pb-2'>Abstract Designs</h3>
               <p className='py-2 font-consolas text-jet text-opacity-85'>
                {" "}
                Creating elegant designs suited for your needs following core design theory.
               </p>
            </div>
            <div className='text-center justify-center shadow-lg px-10 rounded-xl my-1 mx-3 bg-gradient-to-r from-buffyellow to-bananamania'>
              <div className='flex justify-center'>
              <Image src={salon} alt="" width={150} height={150} />
              </div>

               <h3 className='text-lg font-butler text-rosewood pb-2'>Aesthetic Designs</h3>
               <p className='py-2 font-consolas text-jet text-opacity-85'>
                {" "}
                Creating elegant designs suited for your needs following core design theory.
               </p>
            </div>
          </div>
          <div className='flex flex-col gap-10 py-10 lg:flex-row lg:flex-wrap'>
            <div className='basis-1/3 flex-1'>
              <Image src={day1} alt="" className="rounded-lg object-cover" width={'100%'} height={'100%'} responsive/>
            </div>
            <div className='basis-1/3 flex-1'>
              <Image src={day2} alt="" className="rounded-lg object-cover" width={'100%'} height={'100%'} responsive/>
            </div>
            <div className='basis-1/3 flex-1'>
              <Image src={day3} alt="" className="rounded-lg object-cover" width={'100%'} height={'100%'} responsive/>
            </div>
            <div className='basis-1/3 flex-1'>
              <Image src={day4} alt="" className="rounded-lg object-cover" width={'100%'} height={'100%'} responsive/>
            </div>
            <div className='basis-1/3 flex-1'>
              <Image src={day5} alt="" className="rounded-lg object-cover" width={'100%'} height={'100%'} responsive/>
            </div>
            <div className='basis-1/3 flex-1'>
              <Image src={day6} alt="" className="rounded-lg object-cover" width={'100%'} height={'100%'} responsive/>
            </div>
            <div className='basis-1/3 flex-1'>
              <Image src={day7} alt="" className="rounded-lg object-cover" width={'100%'} height={'100%'} responsive/>
            </div>
            <div className='basis-1/3 flex-1'>
              <Image src={day8} alt="" className="rounded-lg object-cover" width={'100%'} height={'100%'} responsive/>
            </div>
            <div className='basis-1/3 flex-1'>
              <Image src={day9} alt="" className="rounded-lg object-cover" width={'100%'} height={'100%'} responsive/>
            </div>
            <div className='basis-1/3 flex-1'>
              <Image src={day10} alt="" className="rounded-lg object-cover" width={'100%'} height={'100%'} responsive/>
            </div>
            <div className='basis-1/3 flex-1'>
              <Image src={day11} alt="" className="rounded-lg object-cover" width={'100%'} height={'100%'} responsive/>
            </div>
            <div className='basis-1/3 flex-1'>
              <Image src={day12} alt="" className="rounded-lg object-cover" width={'100%'} height={'100%'} responsive/>
            </div>
          </div>
        </section>
      </main>
    </div>
  );
}
